### ISSUE TITLE
Data?

### ISSUE THREAD

**Issue by shireenrao** [DonaldWhyte/high-performance-data-processing-in-python-v2#1]
Hello

Loved your talk on algorithmic trading you gave at Pydata Warsaw 2018. Where can I get the pricing data from if I want to try this out?

**Comment by DonaldWhyte** [comment]
The pricing and volume data from this Kaggle dataset were used: https://www.kaggle.com/borismarjanovic/price-volume-data-for-all-us-stocks-etfs

**Comment by DonaldWhyte** [comment]
I've updated the README to include a link to the the dataset. I'll close this issue now, but feel free to reopen if you have any questions.
